CREATE
USER 'dbbackup'@'localhost' IDENTIFIED BY '***';

GRANT
SELECT,
    RELOAD,
    FILE,
    SUPER,
    LOCK TABLES,
    SHOW VIEW
ON *.* TO 'dbbackup'@'localhost' IDENTIFIED BY '***'
WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
